services:
  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: sambura_api
  #   restart: always
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     minio:
  #       condition: service_started
  #   environment:
  #     # PAPO RETO: Aqui tu usa o nome dos serviços do compose!
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: sambura
  #     DB_PASS: sambura_db_secret
  #     DB_NAME: sambura_metadata
  #     SILO_HOST: minio
  #     SILO_PORT_API: 9000
  #     SILO_ACCESS_KEY: sambura_admin
  #     SILO_SECRET_KEY: sambura_silo_secret
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - sambura_net

  postgres:
    image: postgres:15-alpine
    container_name: sambura_db
    environment:
      POSTGRES_USER: sambura
      POSTGRES_PASSWORD: sambura_db_secret
      POSTGRES_DB: sambura_metadata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sambura_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sambura -d sambura_metadata"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sambura_cache
    ports:
      - "6379:6379"
    networks:
      - sambura_net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sambura_broker
    environment:
      RABBITMQ_DEFAULT_USER: sambura_user
      RABBITMQ_DEFAULT_PASS: sambura_mq_secret
    ports:
      - "5672:5672" # Porta para o Core/Worker (AMQP)
      - "15672:15672" # Porta para o Console Web
    networks:
      - sambura_net

  minio:
    image: minio/minio:latest
    container_name: sambura_silo_infra
    environment:
      MINIO_ROOT_USER: sambura_admin
      MINIO_ROOT_PASSWORD: sambura_silo_secret
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web UI
    volumes:
      - storage_data:/data
    command: server /data --console-address ":9001"
    networks:
      - sambura_net

  vault:
    image: hashicorp/vault:latest
    container_name: sambura_vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root_token_sambura 
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - sambura_net
    command: vault server -dev

  vault-init:
    image: hashicorp/vault:latest
    container_name: sambura_vault_init
    depends_on:
      - vault
    networks:
      - sambura_net
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root_token_sambura"
    entrypoint: >
      sh -c "sleep 5;
             vault kv put -mount=secret sambura/database password=sambura_db_secret;
             vault kv put -mount=secret sambura/auth jwt_secret=chave_mestra_sambura_2025 pepper=pimenta_no_reino;
             echo '✅ Vault populado com sucesso, cria!';"

volumes:
  db_data:
  storage_data:

networks:
  sambura_net:
    driver: bridge